using DashboardBackend.Database.Models;
using Model;

namespace DashboardBackend.Parsers
{
    /// <summary>
    /// Converts an <see cref="ExecutionEntry"/> which is generated by EFCore into an <see cref="Execution"/> which is a model created for the Dashboard system.
    /// </summary>
    public class ExecutionParser : IDataParser<ExecutionEntry, List<Execution>>
    {
        /// <inheritdoc/>
        /// <returns>A list of parsed executions.</returns>
        public List<Execution> Parse(List<ExecutionEntry> data)
        {
            return (from item in data
                    let executionId = (int)item.ExecutionId.Value
                    let created = item.Created.Value
                    select new Execution(executionId, created))
                    .ToList();
        }
    }
}
