using DashboardBackend.Database.Models;
using Model;

namespace DashboardBackend.Parsers
{
    /// <summary>
    /// Converts a list of <see cref="EnginePropertyEntry"/> which is generated by EFCore into a list of <see cref="Manager"/>, which is a model created for the Dashboard system.
    /// </summary>
    public class ManagerParser : IDataParser<EnginePropertyEntry, List<Manager>>
    {
        /// <inheritdoc/>
        /// <remarks>The ENGINE_PROPERTIES table of the state database does not contain context ID's or execution ID's, so these are parsed from the log instead.
        /// However, they do have start/end times and rows read/written, and various other details that may be relevant at a later time.</remarks>
        /// <returns>A list of managers without context or execution ID's.</returns>
        public List<Manager> Parse(List<EnginePropertyEntry> data)
        {
            List<Manager> result = new();
            // We will only parse the essential data:
            var filteredData = data.Where(x => x.Key == "START_TIME"
                                            || x.Key == "END_TIME"
                                            || x.Key == "Læste rækker"
                                            || x.Key == "Skrevne rækker");
            foreach (EnginePropertyEntry entry in filteredData)
            {
                string name = entry.Manager.Split(',')[0];
                Manager manager = result.FirstOrDefault(m => m.Name == name && m.ContextId == 0 && m.IsMissingValues);
                if (manager is null)
                {
                    manager = new()
                    {
                        Name = name
                    };
                    result.Add(manager);
                }
                AddEnginePropertiesToManager(manager, entry);
            }
            return result;
        }


        /// <summary>
        /// Parses the value of the specified EnginePropertyEntry and adds it to the given manager.
        /// </summary>
        /// <param name="manager">The manager object associated with the entry.</param>
        /// <param name="entry">The EnginePropertyEntry to get data from.</param>
        private void AddEnginePropertiesToManager(Manager manager, EnginePropertyEntry entry)
        {
            switch (entry.Key)
            {
                case "START_TIME":
                    if (DateTime.TryParse(entry.Value, out DateTime startTime))
                    {
                        manager.StartTime = startTime;
                    }
                    break;
                case "END_TIME":
                    if (DateTime.TryParse(entry.Value, out DateTime endTime))
                    {
                        manager.EndTime = endTime;
                    }
                    break;
                case "Læste rækker":
                    if (int.TryParse(entry.Value, out int rowsRead))
                    {
                        manager.RowsRead = rowsRead;
                    }
                    break;
                case "Skrevne rækker":
                    if (int.TryParse(entry.Value, out int rowsWritten))
                    {
                        manager.RowsWritten = rowsWritten;
                    }
                    break;
                default:
                    break;
            }
        }
    }
}
