using DashboardBackend.Database.Models;
using Model;
using static Model.ValidationTest;

namespace DashboardBackend.Parsers
{
    /// <summary>
    /// Converts a list of <see cref="AfstemningEntry"/> which is generated by EFCore into a list of <see cref="ValidationTest"/>, which is a model created for the Dashboard system.
    /// </summary>
    public class ReconciliationParser : IDataParser<AfstemningEntry, List<ValidationTest>>
    {
        /// <inheritdoc/>
        /// <returns>A list of reconciliations.</returns>
        public List<ValidationTest> Parse(List<AfstemningEntry> data)
        {
            return (from item in data
                    let date = item.Afstemtdato
                    let name = item.Description
                    let managerName = item.Manager
                    let status = GetValidationStatus(item)
                    let srcCount = item.Srcantal
                    let dstCount = item.Dstantal
                    let toolkitId = item.ToolkitId
                    let srcSql = item.SrcSql
                    let dstSql = item.DstSql
                    select new ValidationTest(date, name, status, managerName, srcCount, dstCount, toolkitId, srcSql, dstSql))
                    .ToList();
        }

        /// <summary>
        /// Gets the <see cref="ValidationStatus"/> associated with the specified entry.
        /// </summary>
        /// <param name="entry">The entry to get the type of.</param>
        /// <returns>A <see cref="ValidationStatus"/> that suits the specified entry.</returns>
        /// <exception cref="ArgumentException"/>
        private ValidationStatus GetValidationStatus(AfstemningEntry entry)
        {
            return entry.Afstemresultat switch
            {
                "OK" => ValidationStatus.Ok,
                "DISABLED" => ValidationStatus.Disabled,
                "FAILED" => ValidationStatus.Failed,
                "FAIL MISMATCH" => ValidationStatus.FailMismatch,
                _ => throw new ArgumentException(nameof(entry) + " is not a known reconciliation result.")
            };
        }
    }
}
